version: '3.2'

services:
  db:
    image: mysql:8.0
    container_name: kanban_db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./kabanboard-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  adminer:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: kanban_phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: kanban_db
